AWSTemplateFormatVersion: 2010-09-09
Description:  This template sets up a basic Guard Duty IDS system and links it to an e-mail address provided

Parameters:
  GuardDutyEmail:
    Type: String
    Description: E-mail address to use to receive notifications from the IDS system

Resources:
  # IDS System
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: Fons-IDS
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref GuardDutySNSTopic
      Endpoint: !Ref GuardDutyEmail

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: ONE_HOUR

  GuardDutySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: guardduty-event-topic
      TopicName: guardduty-event-topic
      Subscription:
        - Endpoint: !Join
            - ':'
            - - 'arn:aws:sqs'
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - !Ref SQSQueue
          Protocol: sqs

  GuardDutySNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: Id1
        Statement:
          - Sid: Sid1
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: !Join
              - ':'
              - - 'arn:aws:sns'
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - 'guardduty-event-topic'
      Topics:
        - !Ref GuardDutySNSTopic

  MySNSToSQSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sqs.amazonaws.com
            Action: sns:Publish
            Resource: !Ref GuardDutySNSTopic
      Topics:
        - Ref: GuardDutySNSTopic

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: SQSQueuePolicy
        Statement:
          - Sid: Allow-SendMessage-To-Queue-From-SNS-Topic
            Effect: Allow
            Principal: '*'
            Action:
              - 'sqs:SendMessage'
            Resource: '*'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref GuardDutySNSTopic
      Queues:
        - !Ref SQSQueue
    DependsOn: GuardDutySNSTopic

  GuardDutyEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.guardduty
      Name: guardduty-event-rule
      State: ENABLED
      Targets:
        - Arn: !Join
            - ':'
            - - 'arn:aws:sns'
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - guardduty-event-topic
          Id: 20190702
    DependsOn: GuardDutySNSTopic
