AWSTemplateFormatVersion: 2010-09-09
Description:  Creates Google IdP

Parameters:
  MetadataFile:
    Description: The SAML Metadata file used for the Google SSO application. Google does not provide Metadata URLs so we must provide the raw file itself.
    Type: String
  UserPoolId:
    Description: The User Pool Id to use
    Type: String
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  ApplicationName:
    Description: The name of the application (No Spaces)
    Default: "fons"
    Type: String
  OrganisationName:
    Description: The name of the organisation or la (No Spaces)
    Type: String

Resources:
  UserPoolIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPoolId
      ProviderName: !Sub "${ApplicationName}-${OrganisationName}-GoogleProvider-${EnvironmentName}"
      ProviderDetails:
        MetadataFile: !Ref MetadataFile
      ProviderType: "SAML"
      AttributeMapping:
        email: email
        family_name: family_name
        given_name: given_name
        locale: groups
        name: name

Outputs:
  UserPoolIdentityProvider:
    Description: The User Pool IdP
    Value: !Ref UserPoolIdentityProvider
