name: Package Scaling Lambda

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/environments/cloudformation/full/common/lambda/ecs_scale/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_lambda_base.yml
    with:
      lambda-directory: ./infrastructure/environments/cloudformation/full/common/lambda/ecs_scale
      handler-folder: ecs_scale
      artifact-name: ecs-scaling-lambda
