name: Base Package Lambda

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      lambda-directory:
        required: true
        type: string
      handler-folder:
        required: true
        type: string
      handler-file:
        required: false
        type: string
        default: "handler.py"
      python-version:
        required: false
        type: string
        default: "3.13"
      artifact-name:
        required: true
        type: string
      retention-days:
        required: false
        type: number
        default: 1

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.lambda-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Poetry Export Plugin
        run: poetry self add poetry-plugin-export

      - name: Get lambda version
        id: version
        run: |
          echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Build Lambda package
        run: |
          rm -rf build
          mkdir build

          poetry export \
            -f requirements.txt \
            --output requirements.txt \
            --without-hashes

          python -m pip install \
            -r requirements.txt \
            --target build

          cp ${{ inputs.handler-folder }}/${{ inputs.handler-file }} build/${{ inputs.handler-file }}

      - name: Upload artifact for deploy jobs
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}-${{ steps.version.outputs.version }}
          path: ${{ inputs.lambda-directory }}/build
          retention-days: ${{ inputs.retention-days }}
